_commit: v0.4.61
_src_path: git@github.com:tschm/package.git
description: Backend for the investment-funnel
gh_create: gh repo create tschm/funnel --public --description 'Backend for the investment-funnel'
page: https://tschm.github.io/funnel
project_name: funnel
repository: https://github.com/tschm/funnel
ssh_uri: git@github.com:tschm/funnel.git
status: public
username: tschm
