name: "book"

on:
- push


permissions:
    checks: write
    contents: read

jobs:

  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.56

      - uses: tschm/cradle/actions/marimo@v0.1.56
        with:
          source_folder: book/marimo

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.56

      - uses: tschm/cradle/actions/pdoc@v0.1.56
        with:
          source-folder: src/ifunnel


  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.56

      - uses: tschm/cradle/actions/coverage@v0.1.56
        with:
          tests-folder: src/tests
          source-folder: src/ifunnel
          coveralls: 'false'

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.56

      - uses: tschm/cradle/actions/jupyter@v0.1.56

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter, marimo]

    permissions:
      contents: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Upload the book
        if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
        uses: tschm/cradle/actions/book@v0.1.56
