name: "book"

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to main
on:
  push:
    branches:
      - main


permissions:
    checks: write
    contents: read

jobs:

  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.73

      - uses: tschm/cradle/actions/marimo@v0.1.73
        with:
          source_folder: book/marimo

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.73

      - uses: tschm/cradle/actions/pdoc@v0.1.73
        with:
          source-folder: src/ifunnel


  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.73

      - uses: tschm/cradle/actions/coverage@v0.1.73
        with:
          tests-folder: src/tests
          source-folder: src/ifunnel
          coveralls: false

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.73

      - uses: tschm/cradle/actions/jupyter@v0.1.73

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter, marimo]

    environment:
      name: github-pages  # 👈 this is the critical missing piece

    permissions:
      pages: write            # Permission to deploy to Pages
      id-token: write         # Permission to verify deployment origin

    steps:
      - name: Upload the book
        uses: tschm/cradle/actions/book@v0.1.73
