name: "book"

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to main
on:
  push:
    branches:
      - main


permissions:
    checks: write
    contents: read

jobs:

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.3.01

      - uses: tschm/cradle/actions/pdoc@v0.3.01
        with:
          source-folder: src/ifunnel


  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.3.01

      - uses: tschm/cradle/actions/coverage@v0.3.01
        with:
          tests-folder: src/tests
          source-folder: src/ifunnel
          coveralls: false

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc]

    environment:
      name: github-pages  # 👈 this is the critical missing piece

    permissions:
      pages: write            # Permission to deploy to Pages
      id-token: write         # Permission to verify deployment origin

    steps:
      - name: Upload the book
        uses: tschm/cradle/actions/book@v0.3.01
        with:
          title: 'Funnel'
          links: |
            {
              "API": "./pdoc/index.html",
              "Coverage": "./tests/html-coverage/index.html",
              "Test Report": "./tests/html-report/report.html"
            }
