name: "book"

# This workflow builds and publishes the Jupyter Book for the project
# It runs several jobs in parallel and then combines their outputs

on:
- push


permissions:
    checks: write  # Needed to write check results
    contents: read  # Read access to repository contents

jobs:

  marimo:
    # Process marimo notebooks for inclusion in the book
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.56  # Set up Python environment with dependencies

      - uses: tschm/cradle/actions/marimo@v0.1.56  # Run marimo notebooks and generate outputs
        with:
          source_folder: book/marimo  # Location of marimo notebooks

  pdoc:
    # Generate API documentation using pdoc
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.56  # Set up Python environment with dependencies

      - uses: tschm/cradle/actions/pdoc@v0.1.56  # Generate API documentation
        with:
          source-folder: src/ifunnel  # Source code to document


  test:
    # Run tests and generate coverage reports
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.56  # Set up Python environment with dependencies

      - uses: tschm/cradle/actions/coverage@v0.1.56  # Run tests and generate coverage reports
        with:
          tests-folder: src/tests  # Location of test files
          source-folder: src/ifunnel  # Source code to test
          coveralls: 'false'  # Don't upload to Coveralls in this workflow

  jupyter:
    # Process Jupyter notebooks for inclusion in the book
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.56  # Set up Python environment with dependencies

      - uses: tschm/cradle/actions/jupyter@v0.1.56  # Run Jupyter notebooks and generate outputs

  book:
    # Build and publish the Jupyter Book
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter, marimo]  # Wait for all other jobs to complete

    permissions:
      contents: write  # Need write access to push to gh-pages branch

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4  # Check out the repository code

      - name: Upload the book
        if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
        uses: tschm/cradle/actions/book@v0.1.56  # Build and publish the book to GitHub Pages
