name: Bump version and publish

# This workflow is responsible for creating a new release version and publishing to PyPI
# It automates the versioning, building, and publishing process
on:
  workflow_dispatch:  # This workflow is manually triggered

permissions:
  contents: write  # Permission to write to repository contents (for tagging)

jobs:
  # Job to create a new version tag
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_step.outputs.new_tag }}  # Output the new tag for use in subsequent jobs

    steps:
      - name: Generate Tag
        id: tag_step
        uses: tschm/cradle/actions/tag@v0.3.01
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        # Automatically generates a new version tag based on semantic versioning

  # Job to build the package with the new version
  build:
    runs-on: ubuntu-latest
    needs: tagging  # This job depends on the tagging job
    steps:
      - name: build
        uses: tschm/cradle/actions/build@v0.3.01
        with:
          tag: ${{ needs.tagging.outputs.new_tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        # Builds the package using the new version tag


  # Job to publish the package to PyPI
  publish:
    needs: build  # This job depends on the build job
    runs-on: ubuntu-latest
    environment: release  # Uses the release environment for secrets

    permissions:
      contents: read
      # This permission is required for trusted publishing.
      id-token: write  # Permission for PyPI trusted publishing

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4
        # Checks out the repository code

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
        # Downloads the built distribution files

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # Publishes the package to PyPI using trusted publishing
