name: Bump version and publish

# This workflow creates a new release and publishes the package to PyPI
# It is manually triggered and runs in three sequential steps:
# 1. Create a new version tag
# 2. Build the package
# 3. Publish to PyPI

on:
  workflow_dispatch:  # Manually triggered workflow

permissions:
  contents: write  # Need write access to create tags and releases

jobs:
  tagging:
    # Create a new version tag based on semantic versioning
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_step.outputs.new_tag }}  # Pass the new tag to subsequent jobs

    steps:
      - name: Generate Tag
        id: tag_step
        uses: tschm/cradle/actions/tag@v0.1.57  # Create a new tag and GitHub release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

  build:
    # Build the Python package with the new version
    runs-on: ubuntu-latest
    needs: tagging  # Wait for tagging job to complete
    steps:
      - name: build
        uses: tschm/cradle/actions/build@v0.1.57  # Build the package and create distribution files
        with:
          tag: ${{ needs.tagging.outputs.new_tag }}  # Use the tag from the tagging job


  publish:
    # Publish the package to PyPI using trusted publishing
    needs: build  # Wait for build job to complete
    runs-on: ubuntu-latest
    environment: release  # Use the 'release' environment for PyPI credentials

    permissions:
      contents: read  # Read access to repository contents
      # This permission is required for trusted publishing.
      id-token: write  # Write access to OIDC token for PyPI trusted publishing

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4  # Check out the repository code

      - uses: actions/download-artifact@v4  # Download the built package artifacts
        with:
          name: dist  # Name of the artifact to download
          path: dist  # Path where to download the artifact

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1  # Publish the package to PyPI
